#自定义参数
user:
  #是否启用验证码验证
  captchaEnabled: true
  # 验证码格式：math | char
  captchaType: char
  #是否开启swagger
  swaggerEnabled: false

logging:
  config: classpath:log4j2-product.yml

dubbo:
  registry:
    address: zookeeper://106.15.248.104:2181