#自定义参数
user:
  #是否启用验证码验证
  captchaEnabled: false
  # 验证码格式：math | char
  captchaType: char
  #是否开启swagger
  swaggerEnabled: true

logging:
  config: classpath:log4j2-product.yml

dubbo:
  registry:
    address: zookeeper://172.17.43.184:2181