#自定义参数
user:
  #是否启用验证码验证
  captchaEnabled: false
  # 验证码格式：math | char
  captchaType: math
  #是否开启swagger
  swaggerEnabled: true

logging:
  config: classpath:log4j2-dev.yml

dubbo:
  registry:
    address: zookeeper://127.0.0.1:2181
